### ISSUE TITLE
When suspected, a member does not start spreading Alive with higher incarnation

### ISSUE THREAD

**Issue by localghost** [localghost/membership#36]

**Comment by localghost** [comment]
What's more member does not check if the suspect notification is about itself.

**Comment by kostrzewa9ld** [comment]
Fixed by 195283ebe6bed4aa2c01ce73ab13c51dbdb6d21c

**Comment by localghost** [comment]
Fixed by 195283ebe6bed4aa2c01ce73ab13c51dbdb6d21c
